spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

#lb:// означает load balancer — Spring Cloud Gateway будет искать сервисы по имени в Eureka.
#Что писать в Path=/users/**
#	•	** — это wildcard, подстановочный шаблон.
#	•	/users/** означает: всё, что начинается с /users/ (например, /users, /users/1, /users/create, и т.д.)
#	•	Эти пути проксируются в твой user-service.