#  Управляет всей системой контейнеров сразу. Yml должен видеть все Dockerfile и должен быть в общем корне, чтобы легко обращаться к подпроектам userService и notificationService
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  user-service:
    build:
      context: ./user-service
    depends_on:
      - kafka
      - postgres
      - gateway-api
      - discovery-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports:
      - "8080:8080"

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - kafka
      - gateway-api
      - discovery-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      SPRING_MAIL_HOST: smtp.example.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your_email@example.com
      SPRING_MAIL_PASSWORD: your_password
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    ports:
      - "8081:8081"

  gateway-api:
    build:
      context: ./gateway-api
    ports:
      - "8082:8080"
    depends_on:
      - user-service
      - notification-service
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: default

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"