spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8081

  config:
    import: configserver:http://localhost:8888∑