# Единая точка входа + Circuit Breaker
server:
  port: 8082

spring:
  application:
    name: gateway-api

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCB
                fallbackUri: forward:/fallback/users
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notifCB
                fallbackUri: forward:/fallback/notifications

  resilience4j:
    circuitbreaker:
      instances:
        userCB:
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 2
        notifCB:
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 2

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

#lb:// означает load balancer — Spring Cloud Gateway будет искать сервисы по имени в Eureka.
#Что писать в Path=/users/**
#	•	** — это wildcard, подстановочный шаблон.
#	•	/users/** означает: всё, что начинается с /users/ (например, /users, /users/1, /users/create, и т.д.)
#	•	Эти пути проксируются в твой user-service.