spring:
    application:
        name: config-server

    profiles:
        active: native

    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config

    config:
        import: optional:configserver:http://config-server:8888