server:
  port: 8081

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    config:
      enabled: true

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/users
            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

resilience4j.circuitbreaker:
  instances:
    userCircuitBreaker:
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2