#  Управляет всей системой контейнеров сразу. Yml должен видеть все Dockerfile и должен быть в общем корне, чтобы легко обращаться к подпроектам userService и notificationService

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-user:
    image: postgres:14
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  postgres-notification:
    image: postgres:14
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  user-service:
    build:
      context: ./user-service
    depends_on:
      - kafka
      - postgres-user
      - discovery-service
      - config-server
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports:
      - "8080:8080"

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - kafka
      - discovery-service
      - postgres-notification
      - config-server
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      SPRING_MAIL_HOST: smtp.example.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your_email@example.com
      SPRING_MAIL_PASSWORD: your_password
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    ports:
      - "8081:8081"

  gateway-api:
    build:
      context: ./gateway-api
    ports:
      - "8082:8080"
    depends_on:
      - user-service
      - notification-service
      - discovery-service
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: default

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"

  profile-service:
    build:
      context: ./profile-service
    depends_on:
      - user-service
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: profile-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    ports:
      - "8083:8080"

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: native